# Generated by Django 3.0.7 on 2021-01-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoals', '0002_sugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugar',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
